name: Push On CICD Branch ğŸ§
run-name: ${{ github.actor }} is pushing on CICD ğŸš€
on:
  push:
    branches:
      - 'cicd/*'
jobs:
  Push-On-CICD-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ push on cicd brach ${{ github.event_name }} event."