name: push-on-any ğŸ§
run-name: ${{ github.actor }} push-on-any ğŸš€


on:
  push:
    branches: [ "*" ]  # triggers on any push to any branch

jobs:
  push-on-any-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ On ANY brach by a ${{ github.event_name }} event."
