name: Push On TEST Branch ğŸ§
run-name: ${{ github.actor }} push-on-test-2 ğŸš€
on:
  push:
    branches-ignore:
      - main
      - dev
      - cicd
      - '!test/*'
jobs:
  Push-On-TEST-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Push on test branch by a ${{ github.event_name }} event."
