name: push-on-dev-2 Branch ğŸ§
run-name: ${{ github.actor }} push-on-dev-2 ğŸš€
on:
  push:
    branches:
      - 'dev'
      - main
      - '!test/*'
      - '!dev'
jobs:
  push-on-dev-2-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Push on dev branch by a ${{ github.event_name }} event."

