name: push-on-test Branch ğŸ§
run-name: ${{ github.actor }} push-on-test ğŸš€
on:
  push:
    branches: [ test ]
jobs:
  push-on-test-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Push on test branch by a ${{ github.event_name }} event."
