name: push-on-dev Branch ğŸ§
run-name: ${{ github.actor }} push-on-dev ğŸš€
on:
  push:
    branches:
      - 'dev'
jobs:
  push-on-dev-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Push on dev branch by a ${{ github.event_name }} event."

