name: push-on-main-2 ğŸ§
run-name: ${{ github.actor }} push-on-main-2 ğŸš€
on:
  push:
    branches: [ main ]
jobs:
  push-on-main-2-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Push on main branch by a ${{ github.event_name }} event."
