name: testing-test Branch ğŸ§
run-name: ${{ github.actor }} testing-test ğŸš€
on:
  push
jobs:
  testing-test-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Push on dev branch by a ${{ github.event_name }} event."