name: test-on-main Branch ğŸ§
run-name: ${{ github.actor }} test-on-main ğŸš€
on:
  push:
    branches:
      - main
jobs:
  test-on-main-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Push on dev branch by a ${{ github.event_name }} event."
