name: test-on-test Branch ğŸ§
run-name: ${{ github.actor }} test-on-test ğŸš€
on:
  push:
    branches:
      - test
jobs:
  test-on-test-Branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Push on dev branch by a ${{ github.event_name }} event."
